[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
ua_generator = { version = "^0.5.0", path = "../ua_generator" }
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "generate"
path = "generate.rs"
harness = false