name: Update Crate
on:
  schedule:
    - cron: "0 8 * * *"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and bump
        run: cd ua_generator && BUILD_ENABLED=1 APILAYER_KEY=${{ secrets.APILAYER_KEY }} cargo build
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore(agents): update agent list to latest"
          committer_name: GitHub Actions
          pull: "--rebase --autostash"
